Add-MailboxFolderPermission -Identity brunst:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity hubeda:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity leopst:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity plisge:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity poesha:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity premel:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity schued:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity stubjo:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity thalst:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity ulriul:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity wallal:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity eppira:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity kovves:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity piljma:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity raitst:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity stojiv:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity wolfjo:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity angere:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity aueran:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity jaeglo:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity reinal:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity kronma:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity platmi:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity deutma:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity osmabe:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails
Add-MailboxFolderPermission -Identity schoda:\Kalender -User "IT Mitarbeiter" -AccessRights LimitedDetails