Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=ARNO,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=ARNO,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Benutzer,OU=BAXTER,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Benutzer,OU=BAXTER,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=GRAZ,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=GRAZ,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Benutzer,OU=IBK,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Benutzer,OU=IBK,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=INZ,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=INZ,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=KRAM,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=KRAM,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=LEOG,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=LEOG,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=MATT,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=MATT,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SA14,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SA14,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=IT,OU=Buero,OU=Benutzer,OU=SA14,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=IT,OU=Buero,OU=Benutzer,OU=SA14,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SA22,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SA22,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SAWR,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SAWR,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SCHI,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SCHI,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SML,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SML,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMLL,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMLL,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMS,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMS,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMT,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMT,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=UMKL,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=UMKL,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMBH,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMBH,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMEN,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMEN,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMLE,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMLE,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMLI,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMLI,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMOWS,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMOWS,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMSB,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=WMSB,OU=AT,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=OTTO,OU=DE,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=OTTO,OU=DE,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMHR,OU=HR,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMHR,OU=HR,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMB,OU=HUN,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMB,OU=HUN,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SZOM,OU=HUN,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SZOM,OU=HUN,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMSK,OU=SK,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMSK,OU=SK,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMRS,OU=SRB,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMRS,OU=SRB,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=BUDW,OU=CZ,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=BUDW,OU=CZ,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=CHEM,OU=CZ,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=CHEM,OU=CZ,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMP,OU=CZ,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMP,OU=CZ,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMPL,OU=PL,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMPL,OU=PL,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMTY,OU=PL,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMTY,OU=PL,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=ORAD,OU=RO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=ORAD,OU=RO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMKR,OU=RO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMKR,OU=RO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMRO,OU=RO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMRO,OU=RO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=PERI,OU=SLO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=PERI,OU=SLO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=ROGA,OU=SLO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=ROGA,OU=SLO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMSL,OU=SLO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “true”} | ForEach-Object {Add-ADGroupMember -Identity "GG_Buerouser" -Members $_ }
Get-ADUser -SearchBase "OU=Buero,OU=Benutzer,OU=SMSL,OU=SLO,DC=sal,DC=co,DC=at" -Property Enabled -Filter * | Where-Object {$_.Enabled -like “false”} | ForEach-Object {Remove-ADGroupMember -Identity "GG_Buerouser" -Members $_ -Confirm:$False }